name       : hiredis
version    : 1.0.0
release    : 1
source     :
    - https://github.com/redis/hiredis/archive/v1.0.0.tar.gz : 2a0b5fe5119ec973a0c1966bfc4bd7ed39dbce1cb6d749064af9121fe971936f
license    : BSD-3-Clause
component  : programming.library
summary    : Minimalistic C client for Redis
description: |
    Hiredis is a minimalistic C client library for the Redis database.

    It is minimalistic because it just adds minimal support for the protocol, but at the same time it uses a high level printf-alike API in order to make it much higher level than otherwise suggested by its minimal code base and the lack of explicit bindings for every Redis command.

    Apart from supporting sending commands and receiving replies, it comes with a reply parser that is decoupled from the I/O layer. It is a stream parser designed for easy reusability, which can for instance be used in higher level language bindings for efficient reply parsing.
setup      : |
    %patch -p1 < $pkgfiles/hiredis-cmake-install-destination.patch
    %cmake_ninja -DCMAKE_INSTALL_LIBDIR=lib64 -DENABLE_SSL=ON -DDISABLE_TESTS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
